version: '3.8'

services:
  # mysql:
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   ports:
  #     - ${MYSQL_HOST_PORT}:3306

  # rails:
  #   build:
  #     context: ./rails
  #     dockerfile: .
  #   platform: linux/x86_64
  #   command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   volumes:
  #     - ./rails:/home/app/incubation-match
  #     - bundle:/home/app/incubation-match/vendor/bundle
  #   ports:
  #     - ${RAILS_HOST_PORT}:3000
  #   depends_on:
  #     - mysql

  react:
    build:
      context: ./react
      dockerfile: ./docker/Dockerfile
    command: bash -c "WDS_SOCKET_PORT=${REACT_HOST_PORT} yarn start"
    environment:
      REACT_APP_ENDPOINT: http://localhost:${RAILS_HOST_PORT}
    volumes:
      - ./react:/home/app/stay-in-shimane
      - node_modules:/home/app/stay-in-shimane/node_modules
    ports:
      - ${REACT_HOST_PORT}:3000
      - 6006:6006
    # depends_on:
    #   - rails

volumes:
  # bundle:
  node_modules:
